# Generated by Django 2.2.12 on 2021-07-17 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20210714_1420'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
        migrations.AddField(
            model_name='news',
            name='short_content',
            field=models.TextField(default='', max_length=400),
        ),
    ]
